# Generated by Django 3.0.4 on 2020-06-20 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Название департамента')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Название отдела')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_0.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_duid', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Наименование')),
                ('log_data', models.CharField(blank=True, default=None, max_length=20000, null=True, verbose_name='Информация')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(upload_to='', verbose_name='Аватар')),
                ('position', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Телефон')),
                ('mail', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Е-мейл')),
                ('rating', models.IntegerField(blank=True, default=None, null=True, verbose_name='Рейтинг')),
                ('password', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Пароль')),
                ('date_birth', models.DateTimeField(verbose_name='Дата рождения')),
                ('sex', models.CharField(blank=True, default=None, max_length=1, null=True, verbose_name='Пол')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_0.Department')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_0.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
