# Generated by Django 3.0.4 on 2020-06-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_duid', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Наименование')),
                ('log_data', models.CharField(blank=True, default=None, max_length=20000, null=True, verbose_name='Информация')),
            ],
        ),
    ]
