# Generated by Django 3.0.4 on 2020-06-20 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v0', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Наименование')),
                ('detail', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Срок договора')),
                ('avatar', models.ImageField(upload_to='', verbose_name='Аватар')),
                ('create_duid', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='', verbose_name='Аватар')),
                ('deartment', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Отдел')),
                ('position', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Должность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfferTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Наименование')),
                ('tag_value', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Значение')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='OfferComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default=None, max_length=20000, null=True, verbose_name='Информация')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.Offer')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.Person')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.Person'),
        ),
    ]
