# Generated by Django 3.0.4 on 2020-06-20 14:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0002_auto_20200620_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferAttr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prior_val', models.IntegerField(blank=True, default=None, null=True, verbose_name='Приоритет')),
            ],
        ),
        migrations.CreateModel(
            name='OfferFavorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('person_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='ИД пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='OfferRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('head', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Заголовок')),
                ('detail', models.CharField(blank=True, default=None, max_length=10000, null=True, verbose_name='Текст идеи')),
                ('attach', models.ImageField(upload_to='', verbose_name='Вложение')),
                ('group_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='ИД группы')),
                ('vote_posit', models.IntegerField(blank=True, default=None, null=True, verbose_name='Голосование за')),
                ('vote_negat', models.IntegerField(blank=True, default=None, null=True, verbose_name='Голосование против')),
                ('create_duid', models.DateTimeField(auto_now_add=True)),
                ('prior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='v0.OfferAttr')),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_name',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='person',
        ),
        migrations.RemoveField(
            model_name='offercomment',
            name='person',
        ),
        migrations.RemoveField(
            model_name='offertag',
            name='tag_value',
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Наименование (тип)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='person_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='ИД пользователя'),
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='offercomment',
            name='create_duid',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offercomment',
            name='like',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Лайк'),
        ),
        migrations.AddField(
            model_name='offercomment',
            name='person_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='ИД пользователя'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='detail',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offercomment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offercomment',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='v0.Offer'),
        ),
        migrations.AlterField(
            model_name='offertag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='offerrun',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='v0.OfferTag'),
        ),
        migrations.AddField(
            model_name='offerrun',
            name='type_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.Offer'),
        ),
        migrations.AddField(
            model_name='offerfavorite',
            name='offer_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v0.OfferRun'),
        ),
        migrations.AddField(
            model_name='offer',
            name='prior',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='v0.OfferAttr'),
            preserve_default=False,
        ),
    ]
